[project]
name = "booking_ristourne"
authors = [
    { name = "Wassim Koubaa", email = "koubaawassim@gmail.com"}
]
description = "Application to calculate Cash back and booking for erpnext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
